BAU Remove codacy
alphagov/verify-hub pull request #524
Opened 2021-09-22 13:00 UTC by idrop

Remove codacy report generation - we never look at it

2021-09-22 15:05 UTC, Wynndow approved these changes

2021-09-23 08:47 UTC, CharlesIC approved these changes

2021-09-23 08:52 UTC, CharlesIC requested changes
You'll also need to remove stuff from `build.gradle` and the README

See the original commit to add Codacy ​➔ 7463acce5cf1569be0a3c06e3c596a143b61f7ea

2021-09-27 16:28 UTC, JohnWattsGDS submitted a review, later dismissed
🚀

2021-09-27 16:33 UTC, JohnWattsGDS approved these changes
🚀

2021-09-28 11:17 UTC, CharlesIC approved these changes

2021-09-28 11:19 UTC, merged